{{- $orig := .Values.persistence.originals -}}
{{- if and $orig.enabled (not $orig.nfs.enabled) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "photoprism-plus.fullname" . }}-originals
  labels:
    {{- include "photoprism-plus.labels" . | nindent 4 }}
spec:
  accessModes: {{ toYaml $orig.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ $orig.size }}
{{- if .Values.persistence.storageClassName }}
  storageClassName: {{ .Values.persistence.storageClassName }}
{{- end }}
{{- end }}
