annotations:
  artifacthub.io/category: storage
  artifacthub.io/license: AGPL-3.0-or-later
  artifacthub.io/links: |-
    - name: Documentation
      url: https://docs.photoprism.app/
    - name: Knowledge Base
      url: https://www.photoprism.app/kb
    - name: Support
      url: https://www.photoprism.app/kb/getting-support
  catalog.cattle.io/category: Digital Asset Management (DAM)
  catalog.cattle.io/display-name: PhotoPrism® Plus
  catalog.cattle.io/featured: "true"
  catalog.cattle.io/os: linux
  catalog.cattle.io/requests-cpu: 1000m
  catalog.cattle.io/requests-memory: 1Gi
  catalog.cattle.io/type: app
apiVersion: v2
appVersion: "251130"
description: Deploys PhotoPrism® Plus on Kubernetes with optional portal integration,
  persistent storage, and configurable authentication backends.
home: https://www.photoprism.app/
icon: https://dl.photoprism.app/icons/logo/256.png
keywords:
- photos
- photoprism
- ai
- media
- dam
- webdav
- oidc
maintainers:
- name: PhotoPrism UG
  url: https://www.photoprism.app/contact
name: photoprism-plus
sources:
- https://docs.photoprism.app/
- https://www.photoprism.app/kb
- https://www.photoprism.app/kb/getting-support
- https://github.com/photoprism/photoprism
type: application
version: 0.9.1+251130-b3068414c
