apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "versitygw.fullname" . }}
  labels:
    app: {{ include "versitygw.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "versitygw.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "versitygw.name" . }}
    spec:
      containers:
        - name: versitygw
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - posix
            - --nometa
            - --region
            - {{ .Values.env.VGW_REGION | quote }}
            {{- if .Values.env.VGW_IAM_DIR }}
            - --iam-dir
            - {{ .Values.env.VGW_IAM_DIR | quote }}
            {{- end }}
            - {{ .Values.nfs.bucketsPath }}
          ports:
            - containerPort: 7070
          env:
            {{- if .Values.secret.enabled }}
            - name: ROOT_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.name }}
                  key: {{ .Values.secret.accessKeyName }}
            - name: ROOT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.name }}
                  key: {{ .Values.secret.secretKeyName }}
            {{- else }}
            - name: ROOT_ACCESS_KEY
              value: {{ .Values.env.ROOT_ACCESS_KEY | quote }}
            - name: ROOT_SECRET_KEY
              value: {{ include "versitygw.secretKey" . | quote }}
            {{- end }}
            - name: VGW_BACKEND
              value: {{ .Values.env.VGW_BACKEND | quote }}
            - name: VGW_BACKEND_ARG
              value: {{ .Values.nfs.mountPath | quote }}
            - name: VGW_REGION
              value: {{ .Values.env.VGW_REGION | quote }}
            {{- if .Values.env.VGW_IAM_DIR }}
            - name: VGW_IAM_DIR
              value: {{ .Values.env.VGW_IAM_DIR | quote }}
            {{- end }}
            - name: VGW_HEALTH
              value: {{ .Values.healthProbes.liveness.path | quote }}
          volumeMounts:
            - name: data
              mountPath: {{ .Values.nfs.mountPath }}
          livenessProbe:
            httpGet:
              path: {{ .Values.healthProbes.liveness.path }}
              port: 7070
            initialDelaySeconds: {{ .Values.healthProbes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.healthProbes.liveness.periodSeconds }}
            timeoutSeconds: {{ .Values.healthProbes.liveness.timeoutSeconds }}
            failureThreshold: {{ .Values.healthProbes.liveness.failureThreshold }}
          resources: {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: data
          nfs:
            server: {{ .Values.nfs.server }}
            path: {{ .Values.nfs.path }}
